# Generated by Django 4.2.30 on 2026-06-07 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='catalog.business')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_requests', to='catalog.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
