# Generated by Django 4.2.29 on 2026-04-03 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('catalog', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='communitylike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='communitylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost'),
        ),
        migrations.AlterUniqueTogether(
            name='communitylike',
            unique_together={('post', 'user')},
        ),
    ]
