# Generated by Django 4.2.29 on 2026-04-03 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guiding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideservice',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guiding.guideavailability'),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_bookings_as_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_bookings_as_guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guiding.guideservice'),
        ),
        migrations.AddField(
            model_name='guideavailability',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='guiding.guideservice'),
        ),
        migrations.AlterUniqueTogether(
            name='guideavailability',
            unique_together={('service', 'date', 'start_time')},
        ),
    ]
