# Generated by Django 4.2.29 on 2026-04-03 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gearphoto',
            name='gear_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.gearitem'),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_items', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('gear_item__isnull', False), ('guide_service__isnull', True)), models.Q(('gear_item__isnull', True), ('guide_service__isnull', False)), _connector='OR'), name='wishlist_item_exactly_one_fk'),
        ),
    ]
