# Generated by Django 4.2.29 on 2026-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
