# Generated by Django 4.2.30 on 2026-05-30 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_unit', models.CharField(choices=[('hour', 'Per hour'), ('half_day', 'Per half day'), ('day', 'Per day'), ('week', 'Per week'), ('session', 'Per session')], default='day', max_length=20)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='catalog.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['category__group', 'name'],
            },
        ),
    ]
