"""
Incline Village, NV — Outdoor Adventure Equipment Rental Businesses.

Source of truth for the companion SQLite database and Excel spreadsheet.
Every business and gear item below is sourced from the real business's
public website / price list. See `source` fields for citations.

Last compiled: April 2026.
"""

from __future__ import annotations

from incline_village_rentals.gear_images import attach_gear_images

BUSINESSES = [
    # ──────────────────────────────────────────────────────────────────────
    # 1. Village Ski Loft
    # ──────────────────────────────────────────────────────────────────────
    {
        "slug": "village-ski-loft",
        "name": "Village Ski Loft",
        "business_type": "Multisport (Ski/Board + Bike)",
        "address": "800 Tahoe Blvd",
        "city": "Incline Village",
        "state": "NV",
        "zip": "89451",
        "phone": "(775) 831-3537",
        "email": "villageskiloft@gmail.com",
        "website": "https://www.villageskiloft.com",
        "hours": "Mon–Sun 8:00am–6:00pm (winter); 9:00am–6:00pm (summer)",
        "season": "Year-round (winter: skis/boards; summer: bikes from May)",
        "notes": (
            "North Lake Tahoe's longest-tenured (50+ yrs) ski and bike shop. "
            "Rent 3 days, the 4th is free. Reservations require 48h notice for bikes."
        ),
        "source": "https://www.villageskiloft.com, https://rentals.villageskiloft.com",
        "gear": [
            # Winter – Skis
            {
                "category": "Skis",
                "name": "Adult Performance Ski Package",
                "brand": "Volkl / Salomon",
                "description": "Quality rental package for skiers cruising mostly groomed slopes. Includes skis, bindings, boots, poles.",
                "sizes": "Adult sizes",
                "price": 45.00, "price_unit": "day",
            },
            {
                "category": "Skis",
                "name": "Adult Demo Skis (All-Mountain)",
                "brand": "Atomic / Blizzard / K2 / Nordica",
                "description": "Premium demo package for skiers who ski the whole mountain and want the latest shapes and technology.",
                "sizes": "Adult sizes",
                "price": 65.00, "price_unit": "day",
            },
            {
                "category": "Skis",
                "name": "Junior Ski Package",
                "brand": "Assorted",
                "description": "Affordable, quality rentals for youngest skiers. Junior = size 6 shoe or smaller / skis 140cm or shorter.",
                "sizes": "Jr (≤140cm / ≤size 6 boot)",
                "price": 30.00, "price_unit": "day",
            },
            {
                "category": "Skis",
                "name": "Cross Country Ski Package",
                "brand": "Salomon",
                "description": "Versatile nordic skis for groomed XC centers or blazing your own trail through Mt Rose Meadow.",
                "sizes": "Adult sizes",
                "price": 35.00, "price_unit": "day",
            },
            # Winter – Snowboards
            {
                "category": "Snowboards",
                "name": "Adult Performance Snowboard Package",
                "brand": "Assorted",
                "description": "Quality rental package for riders exploring the whole mountain. Includes board, bindings, boots.",
                "sizes": "Adult sizes",
                "price": 45.00, "price_unit": "day",
            },
            {
                "category": "Snowboards",
                "name": "Adult Demo Snowboard Package",
                "brand": "Assorted",
                "description": "Demo boards for riders wanting latest shapes and tech.",
                "sizes": "Adult sizes",
                "price": 65.00, "price_unit": "day",
            },
            {
                "category": "Snowboards",
                "name": "Junior Snowboard Package",
                "brand": "Assorted",
                "description": "Junior = boots size 6 or smaller / boards 135cm or shorter.",
                "sizes": "Jr (≤135cm / ≤size 6 boot)",
                "price": 30.00, "price_unit": "day",
            },
            # Winter – A la carte
            {
                "category": "Snowshoes & Sleds",
                "name": "Snowshoes",
                "brand": "Assorted",
                "description": "Snowshoe rentals for exploring Mt Rose Meadow, Tahoe Meadows, and surrounding trails.",
                "sizes": "Adult",
                "price": 25.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Adult Skis or Snowboard (no boots)",
                "brand": "Assorted",
                "description": "Skis/boards only, a la carte.",
                "sizes": "Adult",
                "price": 35.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Adult Demo Skis or Snowboard (no boots)",
                "brand": "Assorted",
                "description": "Demo skis/boards only.",
                "sizes": "Adult",
                "price": 55.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Junior Skis or Snowboard (no boots)",
                "brand": "Assorted",
                "description": "Junior a la carte skis or board.",
                "sizes": "Jr",
                "price": 20.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Adult Ski or Snowboard Boots",
                "brand": "Assorted",
                "description": "Boots only.",
                "sizes": "Adult",
                "price": 30.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Junior Ski or Snowboard Boots",
                "brand": "Assorted",
                "description": "Junior boots only.",
                "sizes": "Jr",
                "price": 17.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Bindings",
                "brand": "Assorted",
                "description": "Bindings only.",
                "sizes": "—",
                "price": 30.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Helmet",
                "brand": "Assorted",
                "description": "Helmet rental.",
                "sizes": "Adult/Jr",
                "price": 10.00, "price_unit": "day",
            },
            {
                "category": "A la Carte (Winter)",
                "name": "Poles",
                "brand": "Assorted",
                "description": "Ski poles.",
                "sizes": "—",
                "price": 10.00, "price_unit": "day",
            },
            # Summer – Bikes
            {
                "category": "Bikes",
                "name": "E-Mountain Bike",
                "brand": "Assorted (Santa Cruz, Specialized)",
                "description": "Top-of-the-line full-suspension e-MTBs for riding longer and tackling any climb.",
                "sizes": "S, M, L, XL",
                "price": 120.00, "price_unit": "day",
            },
            {
                "category": "Bikes",
                "name": "Premium Carbon Full-Suspension MTB",
                "brand": "Santa Cruz Bronson / Hightower / Megatower",
                "description": "Premium Carbon Trail bikes for the demanding rider. Handle all the ups and downs of Lake Tahoe.",
                "sizes": "S, M, L, XL",
                "price": 100.00, "price_unit": "day",
            },
            {
                "category": "Bikes",
                "name": "Premium Full-Suspension MTB (Alloy)",
                "brand": "Specialized Stumpjumper Comp Alloy",
                "description": "Staple Tahoe trail bike (not for downhill parks like Northstar).",
                "sizes": "M (5'7–5'9), L (5'10–6'1), XL (6'1+)",
                "price": 80.00, "price_unit": "day",
            },
            {
                "category": "Bikes",
                "name": "Front-Suspension MTB (Hardtail)",
                "brand": "Assorted",
                "description": "Swiss-army bicycle — light-duty trail, fire roads, beach errands.",
                "sizes": "Adult sizes",
                "price": 60.00, "price_unit": "day",
            },
            {
                "category": "Bikes",
                "name": "Electric Cruiser (Turbo Como 2.0)",
                "brand": "Specialized",
                "description": "Comfortable electric cruiser — great for getting to the beach or around Incline.",
                "sizes": "Adult sizes",
                "price": 90.00, "price_unit": "day",
            },
            {
                "category": "Bikes",
                "name": "Cruiser Bike (Roll Sport Disc)",
                "brand": "Specialized",
                "description": "Comfort-geared cruiser. From beach to market.",
                "sizes": "Adult sizes",
                "price": 40.00, "price_unit": "day",
            },
            {
                "category": "Bikes",
                "name": "Kids' Bike",
                "brand": "Assorted",
                "description": "Perfect for junior bikers around town and local trails.",
                "sizes": "Kids",
                "price": 40.00, "price_unit": "day",
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────────
    # 2. Diamond Peak Ski Resort — Rental Shop
    # ──────────────────────────────────────────────────────────────────────
    {
        "slug": "diamond-peak",
        "name": "Diamond Peak Ski Resort — Rental Shop",
        "business_type": "Ski Resort Rental Shop",
        "address": "1210 Ski Way",
        "city": "Incline Village",
        "state": "NV",
        "zip": "89451",
        "phone": "(775) 831-3249",
        "email": "info@diamondpeak.com",
        "website": "https://www.diamondpeak.com",
        "hours": "Season ~8am–4pm daily; early pickup 2–3pm prior afternoon",
        "season": "December – mid-April (ski season)",
        "notes": (
            "On-mountain rental shop and satellite Hyatt Sport Shop (111 Country "
            "Club Dr). $250 CC hold on packages, $700 on demos. Pricing shown is "
            "Value / Weekend / Peak with $10 walk-up surcharge vs online pre-book."
        ),
        "source": "https://diamondpeak.com/lessons-rentals/equipment-rentals",
        "gear": [
            {
                "category": "Ski Package",
                "name": "Adult Ski Package (ages 13+)",
                "brand": "Salomon",
                "description": "Skis, boots, poles, and helmet. Online pre-book price — $10 more at walk-up.",
                "sizes": "Adult",
                "price": 65.00, "price_unit": "day (value)",
                "price_weekend": 80.00, "price_peak": 80.00,
            },
            {
                "category": "Ski Package",
                "name": "Child Ski Package (ages 12 & under)",
                "brand": "Salomon",
                "description": "Skis, boots, poles, and helmet for kids 12 and under.",
                "sizes": "Child",
                "price": 55.00, "price_unit": "day (value)",
                "price_weekend": 70.00, "price_peak": 70.00,
            },
            {
                "category": "Snowboard Package",
                "name": "Adult Snowboard Package (ages 13+)",
                "brand": "Salomon / GNU",
                "description": "Snowboard, boots, and helmet.",
                "sizes": "Adult",
                "price": 65.00, "price_unit": "day (value)",
                "price_weekend": 80.00, "price_peak": 80.00,
            },
            {
                "category": "Snowboard Package",
                "name": "Child Snowboard Package (ages 12 & under)",
                "brand": "Salomon / GNU",
                "description": "Snowboard, boots, and helmet for kids 12 and under.",
                "sizes": "Child",
                "price": 55.00, "price_unit": "day (value)",
                "price_weekend": 70.00, "price_peak": 70.00,
            },
            {
                "category": "Demo",
                "name": "Demo Ski/Snowboard Package",
                "brand": "Salomon, Rossignol, Atomic, Volkl, GNU",
                "description": "Latest demo skis (fat powder, twin tips for men and women) or demo snowboards (park, carving, powder). $700 CC deposit.",
                "sizes": "Adult",
                "price": 90.00, "price_unit": "day (value)",
                "price_weekend": 105.00, "price_peak": 105.00,
            },
            {
                "category": "Demo",
                "name": "Demo Skis or Snowboard Only",
                "brand": "Salomon, Rossignol, Atomic, Volkl, GNU",
                "description": "Demo hardgoods only (no boots).",
                "sizes": "Adult",
                "price": 80.00, "price_unit": "day (value)",
                "price_weekend": 95.00, "price_peak": 95.00,
            },
            {
                "category": "A la Carte",
                "name": "Skis or Snowboard Only",
                "brand": "Salomon",
                "description": "Hardgoods only, no boots/poles.",
                "sizes": "Adult",
                "price": 42.00, "price_unit": "day (flat)",
            },
            {
                "category": "A la Carte",
                "name": "Ski Boots Only",
                "brand": "Salomon",
                "description": "Includes binding check.",
                "sizes": "Adult",
                "price": 37.00, "price_unit": "day (flat)",
            },
            {
                "category": "A la Carte",
                "name": "Snowboard Boots Only",
                "brand": "Salomon",
                "description": "Snowboard boots a la carte.",
                "sizes": "Adult",
                "price": 37.00, "price_unit": "day (flat)",
            },
            {
                "category": "A la Carte",
                "name": "Helmet Only",
                "brand": "Assorted",
                "description": "Ski/snowboard helmet.",
                "sizes": "Adult/Child",
                "price": 10.00, "price_unit": "day (value)",
                "price_weekend": 15.00, "price_peak": 15.00,
            },
            {
                "category": "Lockers",
                "name": "Smartecarte Day Locker",
                "brand": "Smartecarte",
                "description": "Stores shoes and backpacks — must retrieve by 4:30pm.",
                "sizes": "—",
                "price": 13.00, "price_unit": "day (from)",
            },
            {
                "category": "Lockers",
                "name": "Overnight Locker",
                "brand": "—",
                "description": "Fits 3 pairs of adult skis + boots. $30 refundable key deposit.",
                "sizes": "—",
                "price": 30.00, "price_unit": "night",
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────────
    # 3. Tahoe Multisport — Main Shop
    # ──────────────────────────────────────────────────────────────────────
    {
        "slug": "tahoe-multisport",
        "name": "Tahoe Multisport",
        "business_type": "Multisport (Year-Round Gear)",
        "address": "797 Southwood Blvd, Unit 10 (Village Shopping Center)",
        "city": "Incline Village",
        "state": "NV",
        "zip": "89451",
        "phone": "(775) 750-7386",
        "email": "info@tahoemultisport.com",
        "website": "https://tahoemultisport.com",
        "hours": "Seasonal — call for daily hours; year-round",
        "season": "Year-round (summer: SUP/kayak/e-bike; winter: XC ski & backcountry demo)",
        "notes": (
            "Locally owned by JP Donovan & Belinda Quené; also runs a beachfront "
            "rental stand at Incline Beach & Burnt Cedar Beach in summer. Backcountry "
            "ski demos (PRAXIS skis, tech bindings, Montana skins)."
        ),
        "source": "https://tahoemultisport.com",
        "gear": [
            # Summer – Paddle
            {
                "category": "Kayaks (Take-Away)",
                "name": "Single Kayak (Hardshell) — 1 Day",
                "brand": "Assorted sit-on-top",
                "description": "Includes kayak, paddle, seat, dry bag, life jackets, transport straps + padding. Up to 350 lbs.",
                "sizes": "Single",
                "price": 60.00, "price_unit": "day (24hr)",
            },
            {
                "category": "Kayaks (Take-Away)",
                "name": "Double Kayak (Hardshell) — 1 Day",
                "brand": "Assorted sit-on-top",
                "description": "Includes kayak, paddle, seat, dry bag, life jackets, transport straps. Up to 500 lbs; can be paddled as single.",
                "sizes": "Tandem",
                "price": 75.00, "price_unit": "day (24hr)",
            },
            {
                "category": "Kayaks (Take-Away)",
                "name": "Single Inflatable Kayak — 1 Day",
                "brand": "Assorted",
                "description": "24 lbs, 300 lb capacity. Includes pump, paddle, seat, dry bag, life jackets.",
                "sizes": "Single",
                "price": 60.00, "price_unit": "day (24hr)",
            },
            {
                "category": "Kayaks (Take-Away)",
                "name": "Double Inflatable Kayak — 1 Day",
                "brand": "Assorted",
                "description": "30–34 lbs, 500 lb capacity. Includes pump, paddles, seats, dry bag, life jackets.",
                "sizes": "Tandem",
                "price": 75.00, "price_unit": "day (24hr)",
            },
            {
                "category": "Paddleboards (Take-Away)",
                "name": "Inflatable Stand Up Paddleboard — 1 Day",
                "brand": "Assorted",
                "description": "28 lbs, 350 lb capacity. Includes SUP, paddle, kayak seat, dry bag, life jackets, pump, backpack.",
                "sizes": "Single",
                "price": 60.00, "price_unit": "day (24hr)",
            },
            # Beach rentals (Incline Beach & Burnt Cedar)
            {
                "category": "Beach Rental — Kayaks",
                "name": "Single Hobie Mirage Drive Kayak (Beach)",
                "brand": "Hobie",
                "description": "Pedal-drive kayak at Incline Beach / Burnt Cedar. 350–400 lb kayak / 275 lb seat cap. Includes paddles, seats, dry bag, life jackets.",
                "sizes": "Single",
                "price": 50.00, "price_unit": "1 hr",
            },
            {
                "category": "Beach Rental — Kayaks",
                "name": "Feel Free Single Kayak (Beach)",
                "brand": "Feel Free",
                "description": "397 lb capacity. Includes paddle, seat, dry bag, life jacket.",
                "sizes": "Single",
                "price": 35.00, "price_unit": "1 hr",
            },
            {
                "category": "Beach Rental — Kayaks",
                "name": "Feel Free Double Kayak (Beach)",
                "brand": "Feel Free",
                "description": "550–617 lb capacity. Includes paddles, seats, dry bag, life jackets.",
                "sizes": "Tandem",
                "price": 50.00, "price_unit": "1 hr",
            },
            {
                "category": "Beach Rental — Kayaks",
                "name": "Hobie Mirage Eclipse (Stand-Up Pedal)",
                "brand": "Hobie",
                "description": "Stand-up pedal kayak. 300 lb capacity. Includes dry bag, life jackets.",
                "sizes": "Single",
                "price": 55.00, "price_unit": "1 hr",
            },
            {
                "category": "Beach Rental — Kayaks",
                "name": "Clear Kayak (Beach)",
                "brand": "Assorted",
                "description": "Transparent kayak. Includes paddles, seats, dry bag, life jackets.",
                "sizes": "Single/Tandem",
                "price": 55.00, "price_unit": "1 hr",
            },
            {
                "category": "Beach Rental — Kayaks",
                "name": "Kids Kayak (Beach)",
                "brand": "Assorted",
                "description": "Kids sit-on-top kayak. 100 lb capacity. Includes paddle, life jackets.",
                "sizes": "Kids",
                "price": 20.00, "price_unit": "1 hr",
            },
            {
                "category": "Beach Rental — Paddleboards",
                "name": "Clear Paddle Board (Beach)",
                "brand": "Assorted",
                "description": "Transparent SUP. 425 lb capacity. Includes paddle, dry bag, life jackets.",
                "sizes": "Single",
                "price": 40.00, "price_unit": "1 hr",
            },
            # Bikes
            {
                "category": "E-Bikes",
                "name": "Electric Bike Rental",
                "brand": "Assorted",
                "description": "Includes phone holder, rear storage bungee/straps, water bottle holder, helmet, combo bike lock. 350 lb cap, height 4'11\"–6'4\". Toddler seats, equipment/pet trailers, pet carriers, baskets available.",
                "sizes": "Adult (height 4'11\"–6'4\")",
                "price": 65.00, "price_unit": "half day",
                "price_full_day": 100.00,
            },
            {
                "category": "E-Bikes",
                "name": "Rad Runner 3+ Electric Trike",
                "brand": "RadPower",
                "description": "Electric trike. 415 lb cap, height 4'10\"–6'4\". Includes phone holder, bungee, water bottle holder, helmet, lock.",
                "sizes": "Adult (height 4'10\"–6'4\")",
                "price": 65.00, "price_unit": "half day",
                "price_full_day": 100.00,
            },
            # Guided tours
            {
                "category": "Guided Tours",
                "name": "Clear Kayak Tour at Sand Harbor (daily)",
                "brand": "Tahoe Multisport",
                "description": "2 hours on the East Shore paddling clear kayaks around iconic boulders. Includes clear kayaks, paddles, life jackets, dry bags, park shuttle, and entrance fee.",
                "sizes": "Per person",
                "price": 150.00, "price_unit": "per person (from)",
            },
            # Winter
            {
                "category": "Cross-Country Skis",
                "name": "Cross-Country Ski Package",
                "brand": "Salomon",
                "description": "XC skis, poles, boots. Fleet used by Gateway Mountain Center and Incline schools.",
                "sizes": "Adult & Kids",
                "price": 35.00, "price_unit": "day",
            },
            {
                "category": "Backcountry Demo",
                "name": "Backcountry AT Ski Demo",
                "brand": "PRAXIS (skis), Montana (skins)",
                "description": "Backcountry/AT demo skis with tech bindings and Montana skins. DEMO only.",
                "sizes": "Adult",
                "price": 65.00, "price_unit": "day (demo)",
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────────
    # 4. Flume Trail Bikes
    # ──────────────────────────────────────────────────────────────────────
    {
        "slug": "flume-trail-bikes",
        "name": "Flume Trail Bikes",
        "business_type": "Mountain Bike Rentals & Shuttle",
        "address": "1115 Tunnel Creek Rd (behind Tunnel Creek Cafe)",
        "city": "Incline Village",
        "state": "NV",
        "zip": "89451",
        "phone": "(775) 298-2501",
        "email": "info@flumetrailtahoe.com",
        "website": "https://www.flumetrailtahoe.com",
        "hours": "Daily ~9am–5pm (May 15 – November)",
        "season": "May 15 – November",
        "notes": (
            "Located at the Flume Trail trailhead. Offers shuttles and rentals. "
            "Fleet includes Specialized, Ibis, and Kona."
        ),
        "source": "https://www.flumetrailtahoe.com/mountainbikerentals",
        "gear": [
            {
                "category": "Front Suspension MTB",
                "name": "Specialized Fuse Comp (Hardtail)",
                "brand": "Specialized",
                "description": "Well-maintained hardtail with 120mm fork, 27.5x2.80 Ground Control tires, hydraulic brakes, dropper post. Perfect for the Flume Trail.",
                "sizes": "S (5'1–5'7), M (5'5–5'10), L (5'9–6'1), XL (6'0–6'5), XXL (6'6+)",
                "price": 55.00, "price_unit": "day",
            },
            {
                "category": "Full Suspension MTB",
                "name": "Ibis Ripley SL (Carbon, 2026)",
                "brand": "Ibis",
                "description": "NEW 2026 US-made carbon downcountry bike. 117mm DW-link rear, 130mm fork, 66° head angle, ~25.5 lbs, in-frame storage.",
                "sizes": "S (5'0–5'6), M (5'4–5'9), L (5'9–6'1)",
                "price": 100.00, "price_unit": "day",
            },
            {
                "category": "Full Suspension MTB",
                "name": "Ibis Ripley V5 Carbon",
                "brand": "Ibis",
                "description": "\"The bike made for Tahoe.\" 145mm DW-link rear, 140mm front. Shimano Deore 1x12 drivetrain.",
                "sizes": "S (5'0–5'6), M (5'4–5'9), L (5'9–6'1)",
                "price": 95.00, "price_unit": "day",
            },
            {
                "category": "Full Suspension MTB",
                "name": "Specialized Stumpjumper Alloy Comp 29er",
                "brand": "Specialized",
                "description": "M5 alloy frame, 150mm front/rear, 29\" wheels, 2.9\" tires, Shimano brakes, SRAM 1x12.",
                "sizes": "S (5'1–5'6), M (5'5–5'10), XL (6'0–6'5)",
                "price": 75.00, "price_unit": "day",
            },
            {
                "category": "Full Suspension MTB",
                "name": "Specialized Stumpjumper FSR Comp Carbon 29er",
                "brand": "Specialized",
                "description": "Carbon frame, 150mm travel, Fox Factory fork, 15mm through-axle, SRAM 1x12.",
                "sizes": "M (5'6–5'10), L (5'9–6'1), XL (6'0–6'5)",
                "price": 95.00, "price_unit": "day",
            },
            {
                "category": "E-MTB (Pedal Assist)",
                "name": "Ibis OSO Full-Suspension E-MTB",
                "brand": "Ibis",
                "description": "Class 1e pedal assist. Full carbon, upper-link dw-link, 155mm rear / 170mm front, Bosch Performance Line CX motor.",
                "sizes": "M (5'4–5'8), L (5'7–6'1)",
                "price": 120.00, "price_unit": "day",
            },
            {
                "category": "E-MTB (Pedal Assist)",
                "name": "Specialized Turbo Levo Full Suspension",
                "brand": "Specialized",
                "description": "Class 1e pedal assist. The iconic Levo e-MTB.",
                "sizes": "XS (4'11–5'3), S (5'1–5'7), M (5'5–5'10), L (5'9–6'1), XL (5'10–6'5)",
                "price": 120.00, "price_unit": "day",
            },
            {
                "category": "Kids E-MTB",
                "name": "Specialized Turbo Levo SL Kids 24\"",
                "brand": "Specialized",
                "description": "Kid-sized electric MTB, 36.6 lbs, long battery life — kids can keep up with parents on trails.",
                "sizes": "24\" wheel",
                "price": 60.00, "price_unit": "day",
            },
            {
                "category": "Kids MTB",
                "name": "Husqvarna Lite Cross Jr. 24\" Pedal Assist",
                "brand": "Husqvarna",
                "description": "Confidence-building pedal-assist bike for young riders on family trail rides.",
                "sizes": "24\" wheel",
                "price": 60.00, "price_unit": "day",
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────────
    # 5. All Around Tahoe
    # ──────────────────────────────────────────────────────────────────────
    {
        "slug": "all-around-tahoe",
        "name": "All Around Tahoe",
        "business_type": "Watersports & Bike Rentals (Phone-Only Reservations)",
        "address": "Incline Village (delivery to beaches — no storefront)",
        "city": "Incline Village",
        "state": "NV",
        "zip": "89451",
        "phone": "(775) 527-2840",
        "email": "—",
        "website": "https://allaroundtahoe.com",
        "hours": "Daily (summer); phone reservations only",
        "season": "Summer (May – October)",
        "notes": (
            "Phone reservations only. Will deliver to the beach of your choice "
            "(Hidden Beach, Secret Cove, Speedboat Beach, etc.), inflate/deflate gear."
        ),
        "source": "https://allaroundtahoe.com/price-list",
        "gear": [
            {
                "category": "Paddleboards",
                "name": "6-Person Paddleboard (15 ft)",
                "brand": "Assorted (inflatable)",
                "description": "Huge inflatable paddleboard. Paddles and life jackets included.",
                "sizes": "6 person",
                "price": 175.00, "price_unit": "half day (6 hr)",
                "price_full_day": 230.00,
            },
            {
                "category": "Paddleboards",
                "name": "Tandem Paddleboard",
                "brand": "Assorted (inflatable)",
                "description": "Stable tandem SUP. 15 ft, can be used like a kayak with 2 attachable seats.",
                "sizes": "2 person",
                "price": 90.00, "price_unit": "half day (6 hr)",
                "price_full_day": 115.00,
            },
            {
                "category": "Paddleboards",
                "name": "Single Paddleboard",
                "brand": "Assorted (inflatable)",
                "description": "Solo inflatable SUP. Paddle and life jacket included.",
                "sizes": "1 person",
                "price": 60.00, "price_unit": "half day (6 hr)",
                "price_full_day": 90.00,
            },
            {
                "category": "Kayaks",
                "name": "Kayak (Inflatable)",
                "brand": "Assorted (inflatable)",
                "description": "Inflatable kayak. Paddle and life jacket included.",
                "sizes": "Single/Double",
                "price": 60.00, "price_unit": "half day (6 hr)",
                "price_full_day": 90.00,
            },
            {
                "category": "Specialty Watercraft",
                "name": "Swan Boat (6–7 person)",
                "brand": "Assorted",
                "description": "6–7 person swan boat. Delivered inflated to the beach of your choice, retrieved after. Paddles and life jackets included.",
                "sizes": "6–7 person",
                "price": 200.00, "price_unit": "full day",
            },
            {
                "category": "Mountain Bikes",
                "name": "Trek Mountain Bike (Standard)",
                "brand": "Trek",
                "description": "Good for the Flume Trail. Helmet required and included.",
                "sizes": "Assorted adult",
                "price": 20.00, "price_unit": "hour (2 hr min)",
                "price_full_day": 60.00,
            },
            {
                "category": "Mountain Bikes",
                "name": "Flume Trail Mountain Bike",
                "brand": "Assorted",
                "description": "Dialed for Flume Trail. Helmet included.",
                "sizes": "Assorted adult",
                "price": 20.00, "price_unit": "hour (2 hr min)",
                "price_full_day": 60.00,
            },
            {
                "category": "Mountain Bikes",
                "name": "Mountain Bike with Sand Tires",
                "brand": "Assorted",
                "description": "Fat/sand tire MTB for soft surfaces. Helmet included.",
                "sizes": "Assorted adult",
                "price": 20.00, "price_unit": "hour (2 hr min)",
                "price_full_day": 60.00,
            },
            {
                "category": "Accessories",
                "name": "6-Person Blue Floaty",
                "brand": "Assorted",
                "description": "Giant inflatable 6-person floaty for the lake.",
                "sizes": "6 person",
                "price": 175.00, "price_unit": "full day",
            },
            {
                "category": "Accessories",
                "name": "Waterproof Bluetooth Speaker",
                "brand": "Assorted",
                "description": "Bring your music to the lake.",
                "sizes": "—",
                "price": 15.00, "price_unit": "day",
            },
            {
                "category": "Accessories",
                "name": "Beach Wagon",
                "brand": "Assorted",
                "description": "Haul your gear and cooler down to the beach.",
                "sizes": "—",
                "price": 20.00, "price_unit": "day",
            },
            {
                "category": "Accessories",
                "name": "4WD Electric Toy Bronco",
                "brand": "Assorted",
                "description": "Electric toy car for kids to play at the beach.",
                "sizes": "Kids",
                "price": 15.00, "price_unit": "day",
            },
            {
                "category": "Accessories",
                "name": "Dry Bag",
                "brand": "Assorted",
                "description": "Keep your belongings dry.",
                "sizes": "—",
                "price": 15.00, "price_unit": "day",
            },
        ],
    },
]

attach_gear_images(BUSINESSES)
